name: Checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: Use Node.js ${{ matrix.node-version }} # Setup node using version matrix
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: ${{ matrix.node-version }}
      
