name: Checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout" # Download code from the repository
      uses: actions/checkout@v2 # Public action
      with:
        fetch-depth: 0 # Checkout all branches and tags

    - name: "Use NodeJS 16" # Setup node using version 16
      uses: actions/setup-node@v2 # Public action
      with:
        node-version: '16'

      - name: "Setup npm" # Add our registry to npm config
            run: | # Custom action
              npm set @xcanchal:registry=https://npm.pkg.github.com/xcanchal
              npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
            run: | # Install and link dependencies
              npm ci
              npx lerna bootstrap
