name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    - name: Use Node.js ${{ matrix.node-version }} # Setup node using version matrix
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: ${{ matrix.node-version }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }} # Setup node using version matrix
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Setup npm'
        run: |
          npm set @xcanchal:registry=https://npm.pkg.github.com/xcanchal
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
